In [1]:
from dgl.dataloading import GraphDataLoader

Using backend: pytorch


In [2]:
import torch
torch.manual_seed(135)

In [3]:
from prob import VRPDGLDataset
from model import QGNN
from utils import returnState

In [4]:
# load data
data = VRPDGLDataset(num_samples=8)
dataloader = GraphDataLoader(data, batch_size=4)

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 73.38it/s]


In [5]:
model = QGNN(x_feats=2, w_feats=1, e_feats=64).to("cuda")

In [6]:
for d, g in dataloader:
    g = g.to("cuda")
    state = returnState(d)
    action = torch.ones((4,1), device="cuda")
    print(model(g, state, action))
print(model(g, state, action).shape)

tensor([[-5.2325],
        [-2.1401],
        [-1.7746],
        [-1.4457]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-1.1535],
        [-2.5525],
        [-3.5003],
        [-3.0038]], device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([4, 1])


In [7]:
#from train import train
#train(size=50, lr=1e-4, batch=4, num_samples=12)


Generating dataset...


100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 74.52it/s]



Loading routing agent...
  [*] Loading model from ./attention_model/pretrained_tsp/tsp_50\epoch-99.pt

Loading return2depot agent...

Training model...
tensor([[-1.8472],
        [-7.8212],
        [-9.2115],
        [-4.3589]], device='cuda:0', grad_fn=<AddmmBackward0>)


TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'